// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtJK9bN1aBIUU5FXff6qqmlnIUY7cNyZ0',
    appId: '1:783689058798:web:3dff406ae0b0a96fdca6ff',
    messagingSenderId: '783689058798',
    projectId: 'chit-chat-702f1',
    authDomain: 'chit-chat-702f1.firebaseapp.com',
    storageBucket: 'chit-chat-702f1.appspot.com',
    measurementId: 'G-GJK48KPD8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqJOEAKtvJyI26jxmzdViFJS0r-rgM8M',
    appId: '1:783689058798:android:dba958038c7c4507dca6ff',
    messagingSenderId: '783689058798',
    projectId: 'chit-chat-702f1',
    storageBucket: 'chit-chat-702f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzGYoLvCLmJqvBwn9tLpgkvjDbck-WXsM',
    appId: '1:783689058798:ios:2406dd1729fe618adca6ff',
    messagingSenderId: '783689058798',
    projectId: 'chit-chat-702f1',
    storageBucket: 'chit-chat-702f1.appspot.com',
    iosClientId: '783689058798-ikj8689n6guqa4lpc6aon7ac97hf02pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzGYoLvCLmJqvBwn9tLpgkvjDbck-WXsM',
    appId: '1:783689058798:ios:cf0164527ee1270fdca6ff',
    messagingSenderId: '783689058798',
    projectId: 'chit-chat-702f1',
    storageBucket: 'chit-chat-702f1.appspot.com',
    iosClientId: '783689058798-08tfjlgv185es8ohrln6472qjatjej5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
